// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAajgZ8P0vPn4wx2fH4uXmSDKDgfytJLyE',
    appId: '1:981442418723:web:5ac6751c12b7088beef996',
    messagingSenderId: '981442418723',
    projectId: 'authtutorial-ca600',
    authDomain: 'authtutorial-ca600.firebaseapp.com',
    storageBucket: 'authtutorial-ca600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9QAA_LILa4vEXWPWnyvhQF8YUlvkN6xE',
    appId: '1:981442418723:android:b912e61fbafbee65eef996',
    messagingSenderId: '981442418723',
    projectId: 'authtutorial-ca600',
    storageBucket: 'authtutorial-ca600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCI_Txrbzzax1BfedIwSm7cvWQHRKgIc',
    appId: '1:981442418723:ios:e32cf63513236fdfeef996',
    messagingSenderId: '981442418723',
    projectId: 'authtutorial-ca600',
    storageBucket: 'authtutorial-ca600.appspot.com',
    iosBundleId: 'com.example.authentication',
  );
}
